### ISSUE TITLE
replace generic functionalities with opensoar dependency

### ISSUE THREAD

**Issue by GliderGeek** [GliderGeek/PySoar#123]
- [x] add AAT to OpenSoar (https://github.com/GliderGeek/OpenSoar/issues/6)
- [x] add competitor to OpenSoar (https://github.com/GliderGeek/OpenSoar/issues/7)
- [x] add competitionday to OpenSoar (https://github.com/GliderGeek/OpenSoar/issues/8)
- [x]  add soaringspot url functions (https://github.com/GliderGeek/OpenSoar/issues/10)
- [x] add strepla to OpenSoar (https://github.com/GliderGeek/OpenSoar/issues/9)
- [x] make OpenSoar a package (https://github.com/GliderGeek/OpenSoar/issues/13)
- [x] integrate this OpenSoar into PySoar and convert to python3 in the process
   - [x] Perform conversion
   - [x] Test with racetask
   - [x] Test with AAT
   - [x] Test with ENL
   - [x] Test with Strepla daily results
   - [x] fix TODOs

**Comment by GliderGeek** [comment]
- [ ] add AAT to OpenSoar (https://github.com/GliderGeek/OpenSoar/issues/6)
- [ ] add competitor to OpenSoar (https://github.com/GliderGeek/OpenSoar/issues/7)
- [ ] add competitionday to OpenSoar (https://github.com/GliderGeek/OpenSoar/issues/8)
- [ ] add strepla to OpenSoar (https://github.com/GliderGeek/OpenSoar/issues/9)
- [ ] integrate this into PySoar
